# Generated by Django 4.2.3 on 2023-08-10 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams_admin', '0003_alter_semester_id_alter_session_year_id'),
        ('ams_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ams_admin.semester'),
        ),
        migrations.AddField(
            model_name='student',
            name='session_year_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ams_admin.session_year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
