# Generated by Django 4.2.4 on 2023-08-15 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams_admin', '0009_semester_year'),
        ('ams_staff', '0003_alter_student_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ams_admin.staff')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ams_staff.student')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ams_admin.subject')),
            ],
        ),
    ]
