# Generated by Django 4.2.4 on 2023-08-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams_staff', '0004_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
