# Generated by Django 4.2.4 on 2023-08-15 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ams_staff', '0005_attendance_is_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
