# Generated by Django 3.0.5 on 2023-08-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230809_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[(0, 'Admin'), (1, 'Staff'), (2, 'Student')], default=1, max_length=50),
        ),
    ]
