# Generated by Django 4.2.4 on 2023-08-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams_admin', '0005_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
