# Generated by Django 4.2.4 on 2023-08-14 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ams_admin', '0008_alter_staff_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ams_admin.session_year'),
        ),
    ]
